

name : retail_CICD_pipeline
  
on:
    push:
      branches: [ "export" ]
    pull_request:
      branches: [ "export" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup python 3.10
      uses: actions/setup-python@v3
      with :
        python version: "3.10"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt


  build_and_push:
    runs-on: ubuntu-latest
    needs: build_and_test   

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} .

      # üîê Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # üîë Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
            $(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # üöÄ Tag & Push image to ECR
      - name: Tag and Push image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          IMAGE_TAG=latest
          docker tag ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} \
            $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker push \
            $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
